version: 2

jobs:

  build: &build
    docker:
    - image: circleci/golang:1.13
    environment:
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/workspace/mod
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-mod-cache-v1-{{ checksum "./go.sum" }}
        - go-mod-cache-v1-
    - run: go env
    - run: make build
    - save_cache:
        key: go-mod-cache-v1-{{ checksum "./go.sum" }}
        paths:
        - /home/circleci/go/pkg
    - persist_to_workspace:
        root: ./
        paths:
        - .

  prerelease-build:
    <<: *build

  test: &test
    environment:
      GOPATH: /home/circleci/go
    machine: true
    image: ubuntu-1604:201903-01
    working_directory: /home/circleci/workspace/mod
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-mod-cache-v1-{{ checksum "./go.sum" }}
        - go-mod-cache-v1-
    - run:
        name: Install go 1.13
        command: |
          curl https://storage.googleapis.com/golang/go1.13.4.linux-amd64.tar.gz | tar zxvf - go
          sudo rm -rf /usr/local/go
          sudo mv go /usr/local/go
          go version
    - run: make test

  prerelease-test:
    <<: *test

  release:
    environment:
      GOPATH: /home/circleci/go
    docker:
    - image: circleci/golang:1.13
    steps:
    - checkout
    # We can't use attach_workpace due to that CircleCI skips `test` when it is already run before tagging
    - restore_cache:
        keys:
        - go-mod-cache-v1-{{ checksum "./go.sum" }}
        - go-mod-cache-v1-
    - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        filters:
          branches:
            ignore: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - test:
        filters:
          branches:
            ignore: /v[0-9]+(\.[0-9]+)*(-.*)*/
  tagged:
    jobs:
    - prerelease-build:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - prerelease-test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - release:
        requires:
        - prerelease-build
        - prerelease-test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
